$env:WECHATY_PUPPET="wechaty-puppet-xp"
$env:WECHATY_PUPPET_SERVER_PORT="8788"
$env:WECHATY_PUPPET_SERVICE_TOKEN="__token__"
$env:WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER="true"
$env:WECHATY_PUPPET_SERVICE_ENDPOINT="127.0.0.1:8788"
$env:WECHATY_LOG="verbose"

$env:SIGNIN_REALNAME="__realname__"
